services:
  - type: web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT --workers 1